// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjeavdrdqdacrmflbaed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqZWF2ZHJkcWRhY3JtZmxiYWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTI0OTIsImV4cCI6MjA2NjAyODQ5Mn0.XV50Gct9JMX9RcXNt9GyGT7WTyXUB6PpqKaBIIooq4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);